// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: grpc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GRPC_Tun_FullMethodName      = "/proxypro.GRPC/Tun"
	GRPC_TunMulti_FullMethodName = "/proxypro.GRPC/TunMulti"
)

// GRPCClient is the client API for GRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GRPCClient interface {
	Tun(ctx context.Context, opts ...grpc.CallOption) (GRPC_TunClient, error)
	TunMulti(ctx context.Context, opts ...grpc.CallOption) (GRPC_TunMultiClient, error)
}

type gRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCClient(cc grpc.ClientConnInterface) GRPCClient {
	return &gRPCClient{cc}
}

func (c *gRPCClient) Tun(ctx context.Context, opts ...grpc.CallOption) (GRPC_TunClient, error) {
	stream, err := c.cc.NewStream(ctx, &GRPC_ServiceDesc.Streams[0], GRPC_Tun_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &gRPCTunClient{stream}
	return x, nil
}

type GRPC_TunClient interface {
	Send(*Hunk) error
	Recv() (*Hunk, error)
	grpc.ClientStream
}

type gRPCTunClient struct {
	grpc.ClientStream
}

func (x *gRPCTunClient) Send(m *Hunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gRPCTunClient) Recv() (*Hunk, error) {
	m := new(Hunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gRPCClient) TunMulti(ctx context.Context, opts ...grpc.CallOption) (GRPC_TunMultiClient, error) {
	stream, err := c.cc.NewStream(ctx, &GRPC_ServiceDesc.Streams[1], GRPC_TunMulti_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &gRPCTunMultiClient{stream}
	return x, nil
}

type GRPC_TunMultiClient interface {
	Send(*MultiHunk) error
	Recv() (*MultiHunk, error)
	grpc.ClientStream
}

type gRPCTunMultiClient struct {
	grpc.ClientStream
}

func (x *gRPCTunMultiClient) Send(m *MultiHunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gRPCTunMultiClient) Recv() (*MultiHunk, error) {
	m := new(MultiHunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GRPCServer is the server API for GRPC service.
// All implementations must embed UnimplementedGRPCServer
// for forward compatibility
type GRPCServer interface {
	Tun(GRPC_TunServer) error
	TunMulti(GRPC_TunMultiServer) error
	mustEmbedUnimplementedGRPCServer()
}

// UnimplementedGRPCServer must be embedded to have forward compatible implementations.
type UnimplementedGRPCServer struct {
}

func (UnimplementedGRPCServer) Tun(GRPC_TunServer) error {
	return status.Errorf(codes.Unimplemented, "method Tun not implemented")
}
func (UnimplementedGRPCServer) TunMulti(GRPC_TunMultiServer) error {
	return status.Errorf(codes.Unimplemented, "method TunMulti not implemented")
}
func (UnimplementedGRPCServer) mustEmbedUnimplementedGRPCServer() {}

// UnsafeGRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRPCServer will
// result in compilation errors.
type UnsafeGRPCServer interface {
	mustEmbedUnimplementedGRPCServer()
}

func RegisterGRPCServer(s grpc.ServiceRegistrar, srv GRPCServer) {
	s.RegisterService(&GRPC_ServiceDesc, srv)
}

func _GRPC_Tun_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GRPCServer).Tun(&gRPCTunServer{stream})
}

type GRPC_TunServer interface {
	Send(*Hunk) error
	Recv() (*Hunk, error)
	grpc.ServerStream
}

type gRPCTunServer struct {
	grpc.ServerStream
}

func (x *gRPCTunServer) Send(m *Hunk) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gRPCTunServer) Recv() (*Hunk, error) {
	m := new(Hunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GRPC_TunMulti_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GRPCServer).TunMulti(&gRPCTunMultiServer{stream})
}

type GRPC_TunMultiServer interface {
	Send(*MultiHunk) error
	Recv() (*MultiHunk, error)
	grpc.ServerStream
}

type gRPCTunMultiServer struct {
	grpc.ServerStream
}

func (x *gRPCTunMultiServer) Send(m *MultiHunk) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gRPCTunMultiServer) Recv() (*MultiHunk, error) {
	m := new(MultiHunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GRPC_ServiceDesc is the grpc.ServiceDesc for GRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxypro.GRPC",
	HandlerType: (*GRPCServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Tun",
			Handler:       _GRPC_Tun_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "TunMulti",
			Handler:       _GRPC_TunMulti_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc.proto",
}
